# Generated by Django 4.1.2 on 2022-11-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='article',
        ),
    ]
