# Generated by Django 4.1.2 on 2022-11-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardApp', '0004_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modify_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
