# Generated by Django 4.1.2 on 2022-11-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_profile_profile_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
