# Generated by Django 4.1.2 on 2022-12-06 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_follow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='to_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='to_users',
            field=models.ManyToManyField(related_name='to_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
