# Generated by Django 4.1.2 on 2022-12-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_follow_to_users_follow_to_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
